### ISSUE TITLE
Failed to transpile ./lib/syntax_tree/node.rb: SyntaxError — unexpected token tRBRACK

### ISSUE THREAD

**Issue by eregon** [ruby-next/ruby-next#100]
## What did you do?

```
git clone https://github.com/kddnewton/syntax_tree.git
cd syntax_tree
git checkout cb72efc779aa8e9fdc812fc81b495c7998332f21
bundle

gem install ruby-next
ruby-next -V nextify ./lib
```
which shows:
```
RubyNext core strategy: refine
RubyNext transpile mode: rewrite
Remove old files: ./lib/.rbnext
Generated: ./lib/.rbnext/2.3/syntax_tree/basic_visitor.rb
Generated: ./lib/.rbnext/2.3/syntax_tree/cli.rb
Generated: ./lib/.rbnext/2.3/syntax_tree/formatter.rb
Generated: ./lib/.rbnext/2.7/syntax_tree/language_server/inlay_hints.rb
Generated: ./lib/.rbnext/2.7/syntax_tree/language_server.rb
Failed to transpile ./lib/syntax_tree/node.rb: SyntaxError — unexpected token tRBRACK
```

## Additional Context

https://github.com/ruby-syntax-tree/syntax_tree/issues/168

```
$ ruby -rparser/current -rbenchmark -e 'pp Parser::CurrentRuby.parse(File.read("./lib/syntax_tree/node.rb"))'
```
does work, so it seems `parser` can parse it.

## Environment

**Ruby version**: I tried CRuby 3.0 and 3.1

**Ruby Next version:** 0.15.2

**Parser version:** 3.1.2.1

**Unparser version:** 0.6.5

**Comment by eregon** [comment]
I also tried:
```
$ ruby-next nextify --rewrite=pattern-matching,pattern-matching-find-pattern,pattern-matching-in,pattern-matching-oneline-parensless,pattern-matching-pin-vars ./lib
Rewriters not found: pattern-matching,pattern-matching-find-pattern,pattern-matching-in,pattern-matching-oneline-parensless,pattern-matching-pin-vars
Try --list-rewriters to see list of available rewriters
```

**Comment by eregon** [comment]
I noticed this succeeds:
```
$ ruby-next nextify -V --rewrite=pattern-matching ./lib                                        
RubyNext core strategy: refine
RubyNext transpile mode: rewrite
Remove old files: ./lib/.rbnext
Generated: ./lib/.rbnext/syntax_tree/language_server/inlay_hints.rb
Generated: ./lib/.rbnext/syntax_tree/language_server.rb
Generated: ./lib/.rbnext/syntax_tree/node.rb
Generated: ./lib/.rbnext/syntax_tree/parser.rb
```
but this fails:
```
$ ruby-next nextify -V --rewrite=pattern-matching --rewrite=pattern-matching-find-pattern ./lib
RubyNext core strategy: refine
RubyNext transpile mode: rewrite
Remove old files: ./lib/.rbnext
Generated: ./lib/.rbnext/syntax_tree/language_server/inlay_hints.rb
Generated: ./lib/.rbnext/syntax_tree/language_server.rb
Failed to transpile ./lib/syntax_tree/node.rb: SyntaxError — unexpected token tRBRACK
```

**Comment by eregon** [comment]
With the first one, then line 2147 becomes (which TruffleRuby cannot parse: `syntax_tree/lib/.rbnext/syntax_tree/node.rb:2147: syntax error, unexpected '{ arg'`):
```ruby
when (__p_1__ && __p_3__ = (1 == __m_arr__.size) and (Paren(contents: {body: [ArrayLiteral(contents: {parts: [_, _, *]}) => array]}) === __m_arr__[0]))
```
the original is:
```ruby
        in [
             Paren[
               contents: {
                 body: [ArrayLiteral[contents: { parts: [_, _, *] }] => array] }
             ]
           ]
```

**Comment by eregon** [comment]
I noticed that with commenting out `diagnostics.all_errors_are_fatal = true`, but I get the same error and translation for that line, there is still the `ArrayLiteral(contents: {parts: [_, _, *]}) => array`.
So maybe it is a parser gem issue?

**Comment by eregon** [comment]
Adding some debugging in `Parser::Diagnostic::Engine#process`:
```ruby
    def process(diagnostic)
      if ignore?(diagnostic)
        # do nothing
      elsif @consumer
        @consumer.call(diagnostic)
      end

      if raise?(diagnostic)
        p diagnostic
        p diagnostic.message
        p diagnostic.location.line
        p diagnostic.location.source_line
        raise Parser::SyntaxError, diagnostic
      end

      self
    end
```
it shows
```
#<Parser::Diagnostic:0x00007f2c344abc00 @level=:error, @reason=:unexpected_token, @arguments={:token=>"tRBRACK"}, @location=#<Parser::Source::Range (string) 55137...55138>, @highlights=[]>
"unexpected token tRBRACK"
2147
"        when (__p_1__ && __p_3__ = (1 == __m_arr__.size) and (Paren(contents: {body: [ArrayLiteral(contents: {parts: [_, _, *]}) => array]}) === __m_arr__[0]))"
Failed to transpile ./lib/syntax_tree/node.rb: SyntaxError — unexpected token tRBRACK
```
So it seems ruby-next tries to reparse what it produced, and that fails. So maybe the issue is that ruby-next doesn't desugar that `ArrayLiteral(contents: {parts: [_, _, *]}) => array`?

**Comment by eregon** [comment]
I guess `[_, _, *]` is actually "basic" pattern matching, not find pattern. And that should be the case since anyway `syntax_tree` supports CRuby 2.7 and its "basic" pattern matching.

**Comment by palkan** [comment]
Thanks for the investigation, @eregon!

>  when (__p_1__ && __p_3__ = (1 == __m_arr__.size) and (Paren(contents: {body: [ArrayLiteral(contents: {parts: [_, _, *]}) => array]}) === __m_arr__[0]))

> I guess [_, _, *] is actually "basic" pattern matching, not find pattern

These two things look suspicious. I will take a look.

**Comment by palkan** [comment]
Fixed in 0.15.3.

Tested against `syntax_tree` main and 3.6.3 (since @kddnewton got rid of pattern matching recently—performance reasons? Curious to hear more about it 🙂)

**Comment by kddnewton** [comment]
@palkan yeah unfortunately `deconstruct_keys` was showing up quite a lot in the profile. Switching back to a `case..when` gave me some performance back.

I think we can do a better job in CRuby of rewriting the iseqs to do some smarter matching when common patterns are found. Or just let YJIT do its thing. But in the meantime I decided to just roll with eliminating the pattern matching for now.

**Comment by palkan** [comment]
> unfortunately deconstruct_keys was showing up quite a lot in the profile

Yeah, it hasn't been optimized yet. We added some optimization for `#deconstruct` (https://github.com/ruby/ruby/pull/3104) in 3.0, but doing the same for `#deconstruct_keys` is much trickier, since it depends on the args.

> Switching back to a case..when gave me some performance back.

I'm curious, how the transpired code would perform (since transpiled pattern matching is better optimized than a native one). Do you have a benchmark script available somewhere, so I could try to experiment with it?

**Comment by eregon** [comment]
> Fixed in 0.15.3.

Thanks!
I tried `ruby-next nextify -V --rewrite=pattern-matching ./lib` on kddnewton/syntax_tree@cb72efc779aa8e9fdc812fc81b495c7998332f21 and that succeeded.
Together with the change below, the files load on TruffleRuby but the test suite can't be run because it itself uses pattern matching.
I also briefly tried `require "ruby-next/language/runtime"` but that didn't seem to handle `eval` (and it was a pretty high startup overhead).
FWIW I also tried `ruby-next nextify -V --rewrite=pattern-matching ./test/*_test.rb` but that doesn't work, it seems to ignore the 2nd and later files.
It'd be quite convenient to have a mode where the files are rewritten inplace actually for such experiments :)

This is the change to pick up the rewritten lib files under `lib/.rbnext`:
```patch
diff --git a/lib/syntax_tree.rb b/lib/syntax_tree.rb
index 88c6636..04fa0ae 100644
--- a/lib/syntax_tree.rb
+++ b/lib/syntax_tree.rb
@@ -1,5 +1,10 @@
 # frozen_string_literal: true

+if RUBY_ENGINE == "truffleruby"
+  module RubyNext; end
+  $LOAD_PATH.unshift "#{__dir__}/.rbnext"
+end
+
 require "delegate"
 require "etc"
 require "json"
@@ -9,7 +14,7 @@ require "ripper"
 require "stringio"

 require_relative "syntax_tree/formatter"
-require_relative "syntax_tree/node"
+require "syntax_tree/node"
 require_relative "syntax_tree/parser"
 require_relative "syntax_tree/version"

```
Ideally `module RubyNext; end` wouldn't be needed but RubyNext currently adds `using RubyNext;` even if it's only syntax desugaring and no method backports.

**Comment by eregon** [comment]
In general when using RubyNext in a gem I'd want to avoid the runtime dependency, hence I did the manual `$LOAD_PATH.unshift "#{__dir__}/.rbnext"` above.

**Comment by eregon** [comment]
Ah and last thing I noticed this warning when using the runtime mode:
```
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/ruby-next-core-0.15.3/lib/.rbnext/2.7/ruby-next/language/rewriters/2.7/pattern_matching.rb:1010: warning: `_1' is reserved for numbered parameter; consider another name
```

@palkan Would you like I open separate issues with what I mentioned here? Or a single issue with various items?

**Comment by palkan** [comment]
Thanks @eregon!

Let's create separate issues, please. (I will add the "hacktoberfest" label, so the work could be parallelized 🙂).

**Comment by palkan** [comment]
> I also briefly tried require "ruby-next/language/runtime" but that didn't seem to handle eval

Yeah, for eval support, a refinement must be activated explicitly: `using RubyNext::Language::Eval`.

>  but RubyNext currently adds using RubyNext; even if it's only syntax desugaring and no method backports.

You can run `nextify` with `--no-refine` to not inject `using RubyNext`

**Comment by palkan** [comment]
> the test suite can't be run because it itself uses pattern matching.

One option to try adding `-ruby-next` to the Rake task's `ruby_opts` (or add it when running a single test file, `ruby -ruby-next ...`. Haven't tried this though.

**Comment by eregon** [comment]
> You can run `nextify` with `--no-refine` to not inject `using RubyNext`

Oh, right, somehow I missed that in the `--help`.
