### ISSUE TITLE
Enumerable.produce

### ISSUE THREAD

**Issue by palkan** [ruby-next/ruby-next#11]
Links:
- https://bugs.ruby-lang.org/issues/14781
- https://blog.saeloun.com/2019/11/27/ruby-2-7-enumerator-produce

**Comment by Nakilon** [comment]
Feature is linked in bug tracker as Mathematica's `FixedPoint` but it's more `NestWhileList`.  
After [implementing](https://github.com/Nakilon/mll/blob/dece915f19017b4f6ddf477a5a49a5578dd5a74b/lib/mll.rb#L61-L69) it in pure Ruby I used it [like this](https://github.com/Nakilon/mll/blob/dece915f19017b4f6ddf477a5a49a5578dd5a74b/spec/_spec.rb#L1010) a lot in my projects and at work. For some reason my implementation looks much shorter than the `def converge` in bug tracker issue.
