### ISSUE TITLE
Data#initialize doesn't support positional args

### ISSUE THREAD

**Issue by DanilMaximov** [ruby-next/ruby-next#114]
Hi @palkan,

I've noticed an inconsistency in the recent ruby-next release regarding the polyfill for Data classes. 

While standard Ruby Data classes support initialization using both `*args` and `**kwargs`, the polyfill appears to only support `**kwargs`  https://github.com/ruby-next/ruby-next/blob/ba158c530fd523217d33833b4401e20b4129be32/lib/ruby-next/core/data.rb#L73

I receive smth like [this](https://github.com/DanilMaximov/activefunction/actions/runs/7336712757/job/19976455640#step:5:12) in my mock gem ruby-2.* CI builds

I'm eager to contribute a fix for this issue. However, I'm uncertain about the testing strategy for this behavior. I see some related specs https://github.com/ruby-next/ruby-next/blob/ba158c530fd523217d33833b4401e20b4129be32/spec/core/data/initialize_spec.rb#L6-L18, but I'm not sure if they are enabled. Any guidance regarding it would be helpful 🙏 

Thank you!

**Comment by DanilMaximov** [comment]
Just noticed another inconsistent behaviour. Seems like support of creating subclasses through inheritance is missing.

I've attached diff and commits with CI builds highlighting these issue: 
```diff
Commit A...Commit B
-      class Hook < Data.define(:method_name, :before, :after) 
+      Hook = Data.define(:method_name, :before, :after) do
```
- Commit A - https://github.com/DanilMaximov/activefunction/pull/21/commits/247c1738652f78a0c466996b99042dd47322922d
   -  [broken CI pipeline](https://github.com/DanilMaximov/activefunction/actions/runs/7396259236/job/20121022571#step:5:11) 
   -  `ruby-next-core-1.0.0/lib/ruby-next/core/data.rb:75:in 'initialize': undefined method 'size' for nil:NilClass` https://github.com/ruby-next/ruby-next/blob/ba158c530fd523217d33833b4401e20b4129be32/lib/ruby-next/core/data.rb#L73-L75 
- Commit B - https://github.com/DanilMaximov/activefunction/pull/21/commits/fa31eb30405312a928c9935021af63242a31e3bb
    - green CI pipeline

Looks like it's required to copy only `@members` class instance variable on polyfill side so 
```ruby
def self.inherited(subclass)
    subclass.instance_variable_set(:@members, @members) 
end
```
could be enough I guess

**Comment by palkan** [comment]
Hey @DanilMaximov,

>  I see some related specs,  but I'm not sure if they are enabled

They're enabled (and pass).  Could you please provide and example code that caused this issue? (Probably, related to changes in how kwargs are handled in Ruby 2.7; still, we test against older versions).

> Just noticed another inconsistent behaviour. Seems like support of creating subclasses through inheritance is broken.

Good catch 👍 There is no relevant tests in `ruby/spec` (worth contributing 😉). Fixed in https://github.com/ruby-next/ruby-next/commit/fa67eaf8bbf25cd0ceccbcc47527fdc5e4f439e8

**Comment by DanilMaximov** [comment]
> They're enabled (and pass). Could you please provide and example code that caused this issue? (Probably, related to changes in how kwargs are handled in Ruby 2.7; still, we test against older versions).

I've double-checked my case, it was caused by `#initialize` overwriting with smth like this 
```ruby 
def initialize(amount: 20, **) = super
```
, so it's my fault, not ruby-next, sorry 😅

**Comment by DanilMaximov** [comment]
Just faced it again. It appears when Data.new receives Hash as last positional argument, looks like it's 

>  related to changes in how kwargs are handled in Ruby 2.7; 

So need to add 
```ruby
DataSpecs::Measure.new(42, {}) 
```
in specs to reproduce it.

Look's like last Hash positional arg is catched by **new_kwargs here
https://github.com/ruby-next/ruby-next/blob/ba158c530fd523217d33833b4401e20b4129be32/lib/ruby-next/core/data.rb#L35-L39

**Comment by palkan** [comment]
> last Hash positional arg is catched by **new_kwargs here I guess..

Right. And I don't think there is good way to catch this situation (especially when the passed Hash is empty: it's undistinguishable from no kwargs passed (i.e., `new_kwargs` is `{}` for both `Measure.new(42, {})` and `Measure.new(42)`).

I admit it as a limitation (and a wontfix). Added a note to the docs.
