### ISSUE TITLE
Facing issues in new builds impacting production env

### ISSUE THREAD

**Issue by devesh-oyotech** [ruby-next/ruby-next#115]
## What did you do?
Done nothing, no code or config changes done. 

## What did you expect to happen?
Expected to easily deploy a new image given that there is NO change set in the associated repository/code.

## What actually happened?
Getting unknown errors involving below 2 main problems, thereby not enabling a normal deployment with the same code:
1. `/usr/local/bundle/gems/ruby-next-core-1.0.0/lib/.rbnext/2.6/ruby-next/core/data.rb:5: warning: constant ::Data is deprecated`
2. `/usr/local/bundle/gems/redis-rack-3.0.0/lib/rack/session/redis.rb:8:in `<module:Session>': uninitialized constant Rack::Session::Abstract::PersistedSecure (NameError)`

## Additional context
Upon deploying the previously stable image of our code (as of 25 September 2023), the k8s pods are successfully running. But, we are stuck here because we aren't able to push new changes to our stable code as the same stable code only is **now** NOT able to provide a stable service upon trying out a fresh deployment.
 Below is the error that we are getting, causing the associated K8s service pod in CrashLoopBackOff state:
<img width="1440" alt="image" src="https://github.com/ruby-next/ruby-next/assets/110968662/7bafcf32-a0c0-422d-a59f-0013e4a9d9ba">
Adding the same error in text form below:
`
/usr/local/bundle/gems/ruby-next-core-1.0.0/lib/.rbnext/2.6/ruby-next/core/data.rb:5: warning: constant ::Data is deprecated
/usr/local/bundle/gems/ruby-next-core-1.0.0/lib/.rbnext/2.6/ruby-next/core/data.rb:5: warning: constant ::Data is deprecated
/usr/local/bundle/gems/ruby-next-core-1.0.0/lib/.rbnext/2.6/ruby-next/core/data.rb:5: warning: constant ::Data is deprecated
/usr/local/bundle/gems/redis-rack-3.0.0/lib/rack/session/redis.rb:8:in `<module:Session>': uninitialized constant Rack::Session::Abstract::PersistedSecure (NameError)
Did you mean?  Rack::Session::Abstract::Persisted
	from /usr/local/bundle/gems/redis-rack-3.0.0/lib/rack/session/redis.rb:7:in `<module:Rack>'
	from /usr/local/bundle/gems/redis-rack-3.0.0/lib/rack/session/redis.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/redis-rack-3.0.0/lib/redis-rack.rb:3:in `require'
	from /usr/local/bundle/gems/redis-rack-3.0.0/lib/redis-rack.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/redis-actionpack-5.4.0/lib/action_dispatch/middleware/session/redis_store.rb:4:in `require'
	from /usr/local/bundle/gems/redis-actionpack-5.4.0/lib/action_dispatch/middleware/session/redis_store.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/redis-actionpack-5.4.0/lib/redis-actionpack.rb:4:in `require'
	from /usr/local/bundle/gems/redis-actionpack-5.4.0/lib/redis-actionpack.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/redis-rails-5.0.2/lib/redis-rails.rb:4:in `require'
	from /usr/local/bundle/gems/redis-rails-5.0.2/lib/redis-rails.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
	from /src/config/application.rb:7:in `<top (required)>'
	from /src/config/environment.rb:2:in `require_relative'
	from /src/config/environment.rb:2:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:320:in `load_rackup'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:245:in `app'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/runner.rb:157:in `app'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/runner.rb:164:in `start_server'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:275:in `worker'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:139:in `block (2 levels) in spawn_workers'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:139:in `fork'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:139:in `block in spawn_workers'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:135:in `times'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:135:in `spawn_workers'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:213:in `check_workers'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cluster.rb:486:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:186:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cli.rb:80:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:23:in `load'
	from /usr/local/bundle/bin/puma:23:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
	from /usr/local/bin/bundle:30:in `block in <main>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /usr/local/bin/bundle:22:in `<main>'
`

## Environment

**Ruby version**: 2.5.3

**Ruby Next version:** Unknown because we aren't directly using it via the Gemfile. It seems some other library is indirectly using it so we can't confirm the version.

**Parser version:** Unknown because we aren't directly using it via the Gemfile.

**Unparser version:** Unknown because we aren't directly using it via the Gemfile.

**Comment by palkan** [comment]
> Expected to easily deploy a new image given that there is NO change set in the associated repository/code.

It seems that you're not including `Gemfile.lock` file into your repo/Docker context, thus, installing latest (compatible) versions of everything on every build. That's the only explanation why you see Ruby Next 1.0 (released in Dec 2023) in the dependencies. 

The warning `constant ::Data is deprecated` is expected in older Ruby versions (w/o `Data` support) and cannot cause the exception you observe.

My guess is that the `redis-rack` v3.0.0 release (and [this commit](https://github.com/redis-store/redis-rack/commit/db8b382b2afd1fc526507e98f63aa40359734ce9), in particular) caused this issue (though it could be in any other accidentally upgraded dependency). Try pinning `redis-rack` to `~> 2.0`.
