### ISSUE TITLE
can't require on Ruby 3.4.0dev

### ISSUE THREAD

**Issue by ko1** [ruby-next/ruby-next#117]
## What did you do?

`require 'ruby-next'` doesn't work because of `Thread::Backtrace::Location#label` returns with the class name from Ruby 3.4.0dev.

```ruby
      def build_location(trace_locations)
        # The caller_locations behaviour depends on implementaion,
        # e.g. in JRuby https://github.com/jruby/jruby/issues/6055
        while trace_locations.first.base_label != "patch"
          trace_locations.shift
        end
```

`trace_locations` is a result of `caller_locations` (Array) and each entries are `Thread::Backtrace::Location`.
From Ruby 3.4.0dev we changed the return value of `#label` method (https://bugs.ruby-lang.org/issues/19117).

on my environment 
```
["/home/ko1/ruby/install/trunk/lib/ruby/gems/3.4.0+0/gems/ruby-next-core-1.0.1/lib/ruby-next/core.rb:128:in 'Class#new'",
 "/home/ko1/ruby/install/trunk/lib/ruby/gems/3.4.0+0/gems/ruby-next-core-1.0.1/lib/ruby-next/core.rb:128:in 'RubyNext::Core.patch'",
 "/home/ko1/ruby/install/trunk/lib/ruby/gems/3.4.0+0/gems/ruby-next-core-1.0.1/lib/ruby-next/core/kernel/then.rb:6:in '<top (required)>'",
 "<internal:/home/ko1/ruby/install/trunk/lib/ruby/3.4.0+0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'",
 "<internal:/home/ko1/ruby/install/trunk/lib/ruby/3.4.0+0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'"]
```

and `#label` returns `RubyNext::Core.patch` from Ruby 3.4.0dev.

To fix this issue, we simply need to use `#base_label` instead of `#label`.
(or use Regexp to match method name)

----

Now we are trying the new behavior of `Thread::Backtrace::Location`.
If you have further opinion about this specification, please comment on the redmine ticket.

**Comment by palkan** [comment]
Thanks for reporting!

Fixed in https://github.com/ruby-next/ruby-next/commit/7f5e47ec3c5bc6016be9e6855f44bbdf67c4351c (refactored to use `#base_label`)
