### ISSUE TITLE
Symbol arrays with percent notation

### ISSUE THREAD

**Issue by joelmoss** [ruby-next/ruby-next#119]
## What did you do?

Trying to rewrite a Symbol array using percent notation, from this

```ruby
%i[loader @loading]
```

to

```ruby
%i[loader @loading_rewritten]
```

## What actually happened?

The source before rewriting seems to replace the array with a few weird characters...

```
%i_A5Я_ing]
```

and that is before anything is rewritten.

## Additional context

Using this code to debug...

```ruby
def safe_rewrite(source)
  pp source
  pp source.include?('%i[loader @loading]')
end
```

The `include?` call always returns false, even though the `%i[loader @loading]` exists in the source.

thx.

**Comment by palkan** [comment]
Thanks for reporting!

Looks like this part of our _safety_ feature is not complete: https://github.com/ruby-next/ruby-next/blob/1a500f472eef29659519f78deb2dac26e009b086/lib/ruby-next/language/paco_parsers/string_literals.rb#L43

We need to check that `%` is not followed_by `i` (and other non-string literals?). I think, changing to something like below should do the trick:

````diff
- alt(string("%Q"), string("%")),
+ alt(string("%Q"), string("%").not_followed_by(string("i")),
```

Would you like to dig into this and try to provide a patch yourself?)

**Comment by joelmoss** [comment]
So seems my change doesn't actually change/fix anything unless the code has some specifics, which I do not understand.

Here's my rewriter, which right now does not do anything other than print the source...

```ruby
  class SymbolArrayRewriter < RubyNext::Language::Rewriters::Text
    def safe_rewrite(source)
      pp source
      source
    end
  end
```

Now when I pass this code to my rewriter...

```ruby
a = %i[foo bar]
div
```

this is what is printed

`"a = %i_A1Я_iv\n"`

Note the `_iv` at the end.

Now when I pass this to my rewriter

```ruby
a = %i[foo bar]
```

It prints unchanged.

Even this is unchanged...

```ruby
a = %i[foo bar]
d
```

`"a = %i[foo bar]\n" + "d\n"`

Again, all this is with no changes to the code base.

Any ideas? thx

**Comment by palkan** [comment]
> Note the _iv at the end.

Yeah, that's strange; it seems that the parser consumes the first char after the new line and checks if there are any left, and consider the consumed part to be a string.

Let me see what could went unexpectedly wrong here.

**Comment by palkan** [comment]
Okay, I pushed a commit to master that should fix this: https://github.com/ruby-next/ruby-next/commit/3a272343ac00c473de7bca9492d9225027e68cfc

Could you please give it a try?

**Comment by joelmoss** [comment]
Thanks for that, but your fix only seems to work with `#rewrite` and not `#safe_rewrite`.

With `rewrite`, this is maintained and returned as is.

```ruby
%i[foo bar]
```

But with `safe_rewrite`, the above is transformed to...

```ruby
%i[_A1Я_]
```

**Comment by palkan** [comment]
> But with safe_rewrite, the above is transformed to...
> %i[_A1Я_]

That's correct; the contents of the `%[...]` expressions are considered to be literals, so we encode them to avoid transforming them—that's the goal of the `#safe_rewrite`, avoiding accidentally transforming literals.

**Comment by joelmoss** [comment]
hmm, but then if I use `rewrite`, that will not ignore comments, which may cause issues?

**Comment by joelmoss** [comment]
And more to the point `%i[]` is not a string literal. They contain symbols.

**Comment by palkan** [comment]
> that will not ignore comments, which may cause issues?

Comments are not the biggest problem (they don't affect the runtime) but strings used in code—they could be spoiled.

> And more to the point %i[] is not a string literal. They contain symbols.

Well, yeah, but they are identifiers; making them rewritable seems more dangerous to me than the opposite.
