### ISSUE TITLE
Is transpiling to mruby available?

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [ruby-next/ruby-next#41]
Hey @palkan first of all thanks for this awesome gem. I just started looking at it and I see you mention `mruby` in Readme so I wanted to try it out. I did `ruby-next nextify --min-version=mruby
` tried also with a version specified after a dash but it gives me `Malformed version number string mruby`. It would be very useful if you could provide a list of all available versions and how to specify them in transpilation.

**Comment by palkan** [comment]
Hey!

You should use a closest MRI version number to the target mruby. For example, for mruby 2.1.0 it's 2.6.

You can find a working example [here](https://github.com/palkan/acli/blob/535cdd4aa8d4a8335e0e957b5f87371df864e6dd/Rakefile#L102-L118).

Probably, we need a way to specify features to transpile explicitly (it's possible via Ruby API but not exposed to CLI).

**Comment by grzegorz-jakubiak** [comment]
I see thanks

**Comment by palkan** [comment]
Closing this since passing the required rewriters explicitly has been merged and released in 0.9.2
