### ISSUE TITLE
Support for Ruby 2.4

### ISSUE THREAD

**Issue by joshdholtz** [ruby-next/ruby-next#43]
I’m lead maintainer of https://github.com/fastlane/fastlane and I’m so excited about this. I’ve been wanting to use features from newer Ruby versions for so long but not able to since we have been supporting Ruby 2.1 and up for so long.

We have just recently bumped up our minimum to Ruby 2.4 and will probably keep at this for as long as we can. I totally want to respect your time but I am curious in what the effort level would be to support add support down to Ruby 2.4.

I really appreciate all the work you’ve done with this. I’m looking forward to adding this to _fastlane_ as soon as we are able to 😊

**Comment by palkan** [comment]
Hey! Nice to meet you.

Supporting 2.4 shouldn't be too difficult. I'll take a look this week.

**Comment by joshdholtz** [comment]
@palkan Oh my goodness that would be amazing! Thank you very much 😊

**Comment by palkan** [comment]
Just published a pre-release version with Ruby 2.4 support: https://rubygems.org/gems/ruby-next/versions/0.9.0.pre

Here are the instructions on how to use it: https://github.com/ruby-next/ruby-next#using-with-eol-rubies

Please, give it a try and report any issues and/or questions!

**Comment by joshdholtz** [comment]
@palkan Thank you so much! Really appreciate it ❤
