### ISSUE TITLE
Resolve gem_load_path with cleaned path

### ISSUE THREAD

**Issue by mt-kelvintaywl** [ruby-next/ruby-next#62]
Hi guys, first of all, thank you for reading this request and I apologize in advance if my understanding of Ruby is not deep / misjudged.

We have a project that uses `anyway_config` gem and thus have `ruby-next` as a indirect dependency.

My context is that:

I have a project of AWS Lambdas written in Ruby. As we are using the Serverless framework, and specifically the `ruby-package` plugin to help us package our external deps (gems), [it was required for us to install the gems with Bundler's **standalone mode**](https://www.serverless.com/plugins/serverless-ruby-package).

In our project's case, we do `bundle install --standalone --path vendor/bundle`
As such, the generated `bundler/setup.rb` looks something like this (notice the use of relative path resolution `/../`):
```rb
# ./vendor/bundle/bundler/setup.rb
require 'rbconfig'
ruby_engine = RUBY_ENGINE
ruby_version = RbConfig::CONFIG["ruby_version"]
path = File.expand_path('..', __FILE__)
# ... [redacted]
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/ruby-next-core-0.10.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/anyway_config-2.0.6/lib"
```
 > I can see from Bundler's code base that for **standalone mode**, [the gems' lib path are always relative paths to the setup.rb file](https://github.com/rubygems/rubygems/blob/a9b3694abd272ecba32e0d9698496b7e7ea834c4/bundler/lib/bundler/installer/standalone.rb#L46)

As such, $LOAD_PATH can have gem files' lib path to have non-fully-resolved paths (e.g., `/../`).

I was wondering if ruby-next's `language/setup.rb` should try to resolve path first before comparison?
https://github.com/ruby-next/ruby-next/blob/master/lib/ruby-next/language/setup.rb#L51-L53

```diff
-     current_index = $LOAD_PATH.index(dirname)
+     current_index = $LOAD_PATH.map { |p| Pathname.new(p).cleanpath.to_s }.index(dirname)

      raise "Gem's lib is not in the $LOAD_PATH: #{dirname}" if current_index.nil?
```

Sorry for the long explanation, but this was coming from a discussion here:
https://github.com/palkan/anyway_config/issues/71

**Comment by mt-kelvintaywl** [comment]
related to https://github.com/palkan/anyway_config/issues/69,

I am seeing the SyntaxError again on AWS Lambda Ruby 2.7. I wonder if it's related to bundler standalone mode (since we use that for packaging our deps for Lambda).

Would you know if `ruby-next` as a gem work well in cases of standalone mode?

I tried looking up the CI builds here and it seems there are test builds on `bundle install` but not for cases of `bundle install --standalone` 🤔

**Comment by palkan** [comment]
> I wonder if it's related to bundler standalone mode

Yes, it is. Pushed a fix to master.
