### ISSUE TITLE
Ractor backport

### ISSUE THREAD

**Issue by marcandre** [ruby-next/ruby-next#66]
FYI, I just pushed my [`Ractor` backport](https://github.com/marcandre/backports/#ractor), which could be useful for `ruby-next` 😸 

Let me know if I can help.

**Comment by palkan** [comment]
Awesome!

I think, we should add a link to backports to the docs ("Polyfills" section). Something like: "Since Ruby Next uses refinements, it can only extend classes/modules but not add new ones. Consider using Backports if you want, for example, to have Ractor in older Rubies".
WDYT?

**Comment by marcandre** [comment]
I didn't realize that this was a hard limit for `ruby-next`.

Referencing Backports this way sounds good.

There are alternatives to refinements that won't affect the global namespace, for example you could propose something like:

```ruby
module MyGem
  include RubyNext::Polyfills # or whatever API you want here
  
  
  class Foo
    def foo
      Ractor.new { ... }
    end
  end
end

defined?(MyGem::Ractor) # => true
defined?(Ractor) # => false
```

**Comment by palkan** [comment]
> I could edit my backport gem so that it is easy to do.

I like the idea; let's do that!

**Comment by marcandre** [comment]
I reorganized my Ractor backport's code. You may now `require 'backports/ractor/ractor'` and it should define a fully functional `Backports::Ractor`. The implementation needs `Hash#transform_keys!` and `_values!` so I added `using ::RubyNext if defined?(::RubyNext)` to work without my global-level backports.
Let me know if you have a chance to play with it.

**Comment by palkan** [comment]
Finally, I got a change to try it: it works!

However, `include Backports::Ractor` doesn't make `Ractor` available in nested modules, so I had to write `module Some; Ractor = Backports::Ractor;  ...; end` instead. See https://github.com/palkan/faqueue/commit/ae7683a017182dfc885b4a7a5a594c4cd1364303
