### ISSUE TITLE
Incorrect translation of &. evaluating LHS twice

### ISSUE THREAD

**Issue by eregon** [ruby-next/ruby-next#68]
test.rb:
```ruby
p Object.new&.object_id
```

```
$ ruby-next -V --min-version=2.2.0 nextify test.rb         
RubyNext core strategy: refine
RubyNext transpile mode: rewrite
Remove old files: ./.rbnext
Generated: ./.rbnext/2.3/test.rb
```

```
$ cat ./.rbnext/2.3/test.rb
p ((!Object.new.nil? || nil) && Object.new.object_id)
```

But the LHS, `Object.new` should only be evaluated once.

## Environment

**Ruby version**: 2.7

**Ruby Next version:** 0.11.1

**Comment by palkan** [comment]
Thanks for the report!

So far, I have only the following idea:

```
Object.new&.object_id #=> (((__tmp__ = Object.new) || true) && (!__tmp__.nil? || nil) && __tmp__.object_id)
```

(and the lvar name should be unique in the context (file?))

**Comment by eregon** [comment]
Yes, I think an extra var is needed, just like for some cases of pattern matching.

I think it can be simplified a bit:
```ruby
Object.new&.object_id
#=>
(__tmp__ = Object.new; __tmp__.nil? ? nil : __tmp__.object_id)
```
to be closer to the actual behavior, checking with `nil.equal?(__tmp__)` might be better.
