### ISSUE TITLE
Problems with TargetRubyVersion under both standardrb and RuboCop

### ISSUE THREAD

**Issue by todd-a-jacobs** [ruby-next/ruby-next#82]
### Attempted to Use Ruby-Next With Standardrb
With standardrb, I get an ArgumentError exception that says "Malformed version number string" when using "next" as the ruby_version as described in the documentation.

``` yaml
# .standard.yml
require:
  - ruby-next/rubocop
ruby_version: 'next'
parallel: true
ignore:
  - 'lib/.rbnext/**/*'
```

``` bash
$ standardrb
Users/$USER/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:215:in `initialize': Malformed version number string next (ArgumentError)
from /Users/$USER/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
from /Users/$USER/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/gems/standard-1.3.0/lib/standard/loads_yaml_config.rb:27:in `construct_config'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/gems/standard-1.3.0/lib/standard/loads_yaml_config.rb:12:in `call'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/gems/standard-1.3.0/lib/standard/builds_config.rb:19:in `call'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/gems/standard-1.3.0/lib/standard/cli.rb:13:in `run'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/gems/standard-1.3.0/exe/standardrb:7:in `<top (required)>'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/bin/standardrb:23:in `load'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/bin/standardrb:23:in `<main>'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/bin/ruby_executable_hooks:22:in `eval'
from /Users/$USER/.rvm/gems/ruby-2.7.3@tmo_ops_utils/bin/ruby_executable_hooks:22:in `<main>'
```

### Attempted to Use Ruby-Next With RuboCop v1.20.0 and the Standardrb Configuration
``` yaml
# .rubocop.yml
require:
  - ruby-next/rubocop
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 'next'
  Exclude:
    - "lib/.rbnext/**/*"
```

``` bash
# note that there was much trimming of output, which is quite verbose under rubocop,
# but it completed without actual exceptions.

$ rubocop
foo.gemspec:16:32: C: Gemspec/RequiredRubyVersion: required_ruby_version (2.7, declared in foo.gemspec) and TargetRubyVersion (3.01, which may be specified in .rubocop.yml) should be equal.
# almost (or possibly all) Lint/Syntax warnings:
(Using Ruby 3.01 parser; configure using TargetRubyVersion parameter, under AllCops`)
```

Please note that commenting out the inherit_gem directive and the standardrb YAML didn't change the result in any way, except to make RuboCop complain about more things.

## What did you expect to happen?
1. I expected standardrb to run with `ruby_version: 'next'` defined, similar to what's supposed to happen with RuboCop, without raising exceptions.
2. I expected RuboCop not to complain about TargetRubyVersion when set to `next` per the README.
3. I expected ruby-next to handle the use case where the gemspec specifies a minimum Ruby version without complaint, since Ruby-Next is in the runtime dependencies and should handle it smoothly.

## What actually happened?

1. I got exceptions when running standardrb.
2. I got lots of version mismatch complaints from RuboCop when run directly.

## Additional Comments

The addition or removal of additional RuboCop gems like rubocop-rake and rubocop-spec made no difference to the end result in any runs. The same errors were raised. However, it's not clear from the documentation how, where, or if additional RuboCop gems should be required within the YAML files.

## Environment
- macOS 11.6
- GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
- RVM running Ruby 2.7.3p183
- bundler 2.1.4
- bundled gems include:
  - parser 3.0.2.0
  - rubocop 1.20.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.5.0
  - ruby-next 0.13.1
  - ruby-next-core 0.13.1
  - standard 1.3.0
  - unparser 0.6.0

**Comment by todd-a-jacobs** [comment]
@palkan So, in the meantime, what should be the value of the `ruby_version:` key in .standard.yml when using ruby-next? I thought I had understood the directions in the README for standardrb (see example [.standard.ym](https://github.com/testdouble/standard#what-you-might-do-if-youre-clever), which includes a ruby_version key), but maybe this is partly just a misunderstanding on my part about how to properly integrate ruby-next with standardrb.

If I understand what was needed, I'd be happy to make a documentation PR, but at the moment I'm simply unable to integrate it or understand where I've gone wron. The fault isn't all on ruby-next; I have some bugs open for standardrb, too. :)

Thanks for being so responsive, and for putting together such a cool and much-needed gem!

**Comment by todd-a-jacobs** [comment]
@palkan There’s a [PR on standardrb](https://github.com/testdouble/standard/pull/342) that could probably use your input to support or resolve this issue.

**Comment by palkan** [comment]
Hey @todd-a-jacobs!

I see that the PR to Standard has been merged. Did it solved the problem?

**Comment by todd-a-jacobs** [comment]
> I see that the PR to Standard has been merged. Did it solved the problem?

I haven't tested it myself, but upstream thinks it's been fixed. We can go ahead and close this.
