### ISSUE TITLE
ruby-next causes random segmentation faults in Ruby 2.7.x

### ISSUE THREAD

**Issue by tomdalling** [ruby-next/ruby-next#93]
## What did you do?

Included the `anyway_config` gem into a Rails project.

## What did you expect to happen?

It should not segfault.

## What actually happened?

Segfaults happen randomly in code unrelated to `anyway_config`.

## Additional context

I've uploaded [a reproduction script to the Ruby bug tracker](https://bugs.ruby-lang.org/issues/17382).

The segfaults _do not_ happen using `anyway_config` v2.0.0.pre2, and _do_ happen using v2.0.0.rc1. The newer version introduced `ruby-next`, so I'm assuming that is the cause.

Only happens on Ruby 2.7.x. Ruby 3.0.3 and 3.1.1 both appear to be ok.

I'm not sure if you'll be able to fix this or if it's a Ruby core bug, but I thought I would report it here anyway.

## Environment

**Ruby version**: 2.7.5

**Ruby Next version:** `ruby-next-core (0.14.1)`

**Parser version:** `parser (3.1.1.0)`

**Unparser version:** not used.

**Comment by palkan** [comment]
Did some investigation and posted the results to the Ruby tracker.
Since it's not related to Ruby Next, closing this one in favour or https://github.com/palkan/anyway_config/issues/100.

**Comment by tomdalling** [comment]
Awesome, thanks for investigating.
