### ISSUE TITLE
Truffleruby Compatbility

### ISSUE THREAD

**Issue by ollym** [ruby-next/ruby-next#96]
Related to this https://github.com/palkan/anyway_config/issues/103

The issue is here:
https://github.com/palkan/anyway_config/blob/master/lib/anyway/tracing.rb#L10

Truffleruby will claim `3.0.3` in `RUBY_VERSION` but doesn't yet support endless method definition.

**Comment by palkan** [comment]
Should be fixed in 0.15.2
