### ISSUE TITLE
Ruby 3.2 Data

### ISSUE THREAD

**Issue by palkan** [ruby-next/ruby-next#98]
https://bugs.ruby-lang.org/issues/16122

**Comment by saturnflyer** [comment]
I pulled this project down to investigate how to add the core `Data` class but it wasn't immediately obvious to me.
So I created http://github.com/saturnflyer/polyfill-data
I'd like to contribute that work to `ruby-next`. Is there a guide somewhere to point out how to manage core classes?

**Comment by palkan** [comment]
Hey!

> So I created [http://github.com/saturnflyer/polyfill-data](https://github.com/saturnflyer/polyfill-data)

Looks great!

> Is there a guide somewhere to point out how to manage core classes?

Not yet. That's the first class we'd like to add (we only [add `NoMatchingPatternError`](https://github.com/ruby-next/ruby-next/blob/cabf5829ee6939d23481ed74eb20809e2191eeac/lib/ruby-next/core.rb#L180)).

I think, we need to make using Data explicit (and thus, optional). So, force users to add smth like this to their code:

```ruby
require "ruby-next/core/data"
```

For testing, we should copy the contents of the `ruby/spec` specs: https://github.com/ruby/spec/tree/master/core/data

Finally, for the `ruby-next core_ext` command, we need to add a patch definition like this: https://github.com/ruby-next/ruby-next/blob/master/lib/ruby-next/core/constants/no_matching_pattern_error.rb (we can use `File.read(File.open(....))` to get the source code from the `ruby-next/core/data.rb`).

**Comment by palkan** [comment]
Hey!

I ended up copying your implementation and adding some minor changes (to comply with the spec). Thanks!
